//Error
export const GET_ERRORS = "GET_ERRORS";

//Auth
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//Course
export const ADD_COURSE = "ADD_COURSE";
export const GET_COURSES = "GET_COURSES";
export const GET_COURSES_BY_FILTER = "GET_COURSES_BY_FILTER";
export const GET_COURSE = "GET_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const COURSE_LOADING = "COURSE_LOADING";

//Member
export const GET_STUDENTS = "GET_STUDENTS";
export const GET_ALLSTUDENTS = "GET_ALLSTUDENTS";
export const ADD_STUDENT = "ADD_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const MEMBER_LOADING = "MEMBER_LOADING";

//Collection
export const GET_QUESTION = "GET_QUESTION";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const ADD_QUESTION = "ADD_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const QUESTION_LOADING = "QUESTION_LOADING";

//Assignment
export const GET_ASSIGNMENT = "GET_ASSIGNMENT";
export const GET_ASSIGNMENTS = "GET_ASSIGNMENTS";
export const ADD_ASSIGNMENT = "ADD_ASSIGNMENT";
export const SUBMIT_QUESTION = "SUBMIT_QUESTION";
export const GET_QUESTIONS_BY_ASSIGNMENT = "GET_QUESTIONS_BY_ASSIGNMENT";
export const GET_QUESTION_IN_ASSIGNMENT = "GET_QUESTION_IN_ASSIGNMENT";
export const DELETE_ASSIGNMENT = "DELETE_ASSIGNMENT";
export const UPDATE_ASSIGNMENT = "UPDATE_ASSIGNMENT";
export const ASSIGNMENT_LOADING = "ASSIGNMENT_LOADING";

//Score book
export const GET_SCORE="GET_SCORE";
export const GET_SCORES="GET_SCORES";
export const UPDATE_SCORE="UPDATE_SCORE";
export const SCORE_LOADING="SCORE_LOADING";