export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CREATE_COURSE = "CREATE_COURSE";
export const GET_COURSES = "GET_COURSES";
export const COURSE_LOADING = "COURSE_LOADING"